### ISSUE TITLE
Unclear instructions to use as dependency.

### ISSUE THREAD

**Issue by biggestsonicfan** [NiconDevTeam/NiconNotifyOSD#2]
Greetings,

The project [dinawall_core](https://github.com/NiconDevTeam/dinawall_core) references this project as a dependency. However in it's build.gradle, it [lists the following](https://github.com/NiconDevTeam/dinawall_core/blob/f4a9358026f6b296f1bd8d48349f7bd690e0819a/build.gradle#L16):
>    implementation          files('../lib/NiconNotifyOSD.jar')

There are no instructions how to turn the NiconNotifyOSD repository into a NiconNotifyOSD.jar file, unless I am missing something simple and assumed.

Thank you.

**Comment by biggestsonicfan** [comment]
I believe the issue is caused by the deletion of build.xml, build-impl.xml, genfiles.properies, project.properties, and project.xml in commits 81f982522ed2804ce677141aeb06f349f83c7675 43f7fb788df91d1ca973ba859bbd7430049c46c7 e6bb266ed6969a9761f520005576faa3ba1b8c24 4cd7c4c0d8e79d37d0e39579cf6f74454c7b4ca3 and 86e1eebf722a24dbb977cca33daa1195a3f4fc07. These were essential for building NiconNotifyOSD.jar, so I suggest you revert to commit 43bab00166cf52bbf1c51ec0d31a02463e853687.

**Comment by fredericksalazar** [comment]
Hello, thank you very much for writing, I apologize for not responding sooner.

NiconNotifyOSD only contains the src source code, so I'm going to turn it into a gradle project. so I can implement tasks for compilation and packaging.

Now, in order to use it with dinawall_core, then I am going to create a lib folder inside dinawall_core with which you can use it as a dependency. I will do this today.

On the other hand then I also see the possibility of publishing NiconNotifyOSD in mavencentral so that it can be loaded as a dependency from a centralized repository.

Thank you very much for your support and interest.

**Comment by fredericksalazar** [comment]
ok, I just updated the main branch of dinawall_core by adding a lib folder that contains the latest version of NiconNotifyOSD.jar and that you can use as a dependency for the dinawall_core project. This is the partial solution, as I mentioned before I am going to retake the NiconNotifyOSD to convert it to Gradle and add tasks for compilation and packaging. thank you have a great day and do not hesitate to write me

**Comment by biggestsonicfan** [comment]
Closing as the issue is very stale and I no longer use Linux as a daily driver.
